# Импорт данных с экономией памяти

## Принципы импорта

Опираемся на текущую документацию и на фактические CSV.

Что делаем для экономии памяти:
- не читаем `Unnamed: 0`;
- пропускаем поля, которые в документации помечены как ненужные, а также тяжёлые детали вроде `results`;
- читаем числа с `thousands=","`, потому что ID в CSV записаны с разделителями тысяч;
- сразу переводим low-cardinality строки в `category`;
- downcast-им числовые столбцы до `Int8/Int16/Int32` и `Float32`, где это безопасно.

In [6]:
from pathlib import Path

import pandas as pd

SRC_DIR = Path.cwd() / "src"

In [7]:
# Базовые таблицы: пользователи, курсы и структура курса.
users_df = pd.read_csv(
    SRC_DIR / "users.csv",
    usecols=[
        "id",
        "last_explainer_seen_→_course",
        "created_at",
        "updated_at",
        "type",
        "sign_in_count",
        "grade_id",
        "subscribed",
        "is_teacher",
        "timezone",
        "grade_changed_at",
        "d_wk_school_id",
        "d_wk_municipal_id",
        "d_wk_region_id",
        "wk_gender",
    ],
    thousands=",",
    low_memory=False,
)
users_df["created_at"] = pd.to_datetime(users_df["created_at"], format="%d %b, %Y, %H:%M", errors="coerce")
users_df["updated_at"] = pd.to_datetime(users_df["updated_at"], format="%d %b, %Y, %H:%M", errors="coerce")
users_df["grade_changed_at"] = pd.to_datetime(users_df["grade_changed_at"], format="%d %b, %Y, %H:%M", errors="coerce")
users_df["id"] = users_df["id"].astype("Int32")
users_df["last_explainer_seen_→_course"] = users_df["last_explainer_seen_→_course"].astype("Int8")
users_df["sign_in_count"] = users_df["sign_in_count"].astype("Int32")
users_df["grade_id"] = users_df["grade_id"].astype("Int16")
users_df["d_wk_school_id"] = users_df["d_wk_school_id"].astype("Int32")
users_df["d_wk_municipal_id"] = users_df["d_wk_municipal_id"].astype("Int32")
users_df["d_wk_region_id"] = users_df["d_wk_region_id"].astype("Int32")
users_df["wk_gender"] = users_df["wk_gender"].astype("Int8")
users_df["type"] = users_df["type"].astype("category")
users_df["timezone"] = users_df["timezone"].astype("category")
users_df["subscribed"] = users_df["subscribed"].astype("boolean")
users_df["is_teacher"] = users_df["is_teacher"].astype("boolean")

users_courses_df = pd.read_csv(
    SRC_DIR / "users_courses.csv",
    usecols=[
        "user_id",
        "course_id",
        "state",
        "created_at",
        "updated_at",
        "access_finished_at",
        "wk_points",
        "wk_max_points",
        "wk_max_viewable_lessons",
        "wk_max_task_count",
        "wk_officially_started_at",
        "wk_course_completed_at",
    ],
    thousands=",",
    low_memory=False,
)
users_courses_df["created_at"] = pd.to_datetime(users_courses_df["created_at"], format="%d %b, %Y, %H:%M", errors="coerce")
users_courses_df["updated_at"] = pd.to_datetime(users_courses_df["updated_at"], format="%d %b, %Y, %H:%M", errors="coerce")
users_courses_df["access_finished_at"] = pd.to_datetime(users_courses_df["access_finished_at"], format="%d %b, %Y", errors="coerce")
users_courses_df["wk_officially_started_at"] = pd.to_datetime(users_courses_df["wk_officially_started_at"], format="%d %b, %Y", errors="coerce")
users_courses_df["wk_course_completed_at"] = pd.to_datetime(users_courses_df["wk_course_completed_at"], format="%d %b, %Y, %H:%M", errors="coerce")
users_courses_df["user_id"] = users_courses_df["user_id"].astype("Int32")
users_courses_df["course_id"] = users_courses_df["course_id"].astype("Int32")
users_courses_df["wk_points"] = users_courses_df["wk_points"].astype("Float32")
users_courses_df["wk_max_points"] = users_courses_df["wk_max_points"].astype("Float32")
users_courses_df["wk_max_viewable_lessons"] = users_courses_df["wk_max_viewable_lessons"].astype("Float32")
users_courses_df["wk_max_task_count"] = users_courses_df["wk_max_task_count"].astype("Float32")
users_courses_df["state"] = users_courses_df["state"].astype("category")

lessons_df = pd.read_csv(
    SRC_DIR / "lessons.csv",
    usecols=[
        "course_id",
        "conspect_expected",
        "task_expected",
        "lesson_number",
        "wk_max_points",
        "wk_task_count",
        "wk_survival_training_expected",
        "wk_scratch_playground_enabled",
        "wk_attendance_tracking_enabled",
        "wk_video_duration",
        "wk_attendance_tracking_disabled_at",
    ],
    parse_dates=["wk_attendance_tracking_disabled_at"],
    thousands=",",
    low_memory=False,
)
lessons_df["course_id"] = lessons_df["course_id"].astype("Int32")
lessons_df["lesson_number"] = lessons_df["lesson_number"].astype("Float32")
lessons_df["wk_max_points"] = lessons_df["wk_max_points"].astype("Float32")
lessons_df["wk_task_count"] = lessons_df["wk_task_count"].astype("Float32")
lessons_df["wk_video_duration"] = lessons_df["wk_video_duration"].astype("Float32")

user_access_histories_df = pd.read_csv(
    SRC_DIR / "user_access_histories.csv",
    usecols=["users_course_id", "access_started_at", "access_expired_at", "activator_class"],
    thousands=",",
    low_memory=False,
)
user_access_histories_df["access_started_at"] = pd.to_datetime(user_access_histories_df["access_started_at"], format="%d %b, %Y", errors="coerce")
user_access_histories_df["access_expired_at"] = pd.to_datetime(user_access_histories_df["access_expired_at"], format="%d %b, %Y", errors="coerce")
user_access_histories_df["users_course_id"] = user_access_histories_df["users_course_id"].astype("Int32")
user_access_histories_df["activator_class"] = user_access_histories_df["activator_class"].astype("category")

In [8]:
# Логи прохождения курса.
user_lessons_df = pd.read_csv(
    SRC_DIR / "user_lessons.csv",
    usecols=[
        "user_id",
        "lesson_id",
        "group_id",
        "video_visited",
        "translation_visited",
        "users_course_id",
        "solved",
        "solved_tasks_count",
        "wk_points",
        "video_viewed",
        "wk_solved_task_count",
    ],
    thousands=",",
    low_memory=False,
)
user_lessons_df["user_id"] = user_lessons_df["user_id"].astype("Int32")
user_lessons_df["lesson_id"] = user_lessons_df["lesson_id"].astype("Int32")
user_lessons_df["group_id"] = user_lessons_df["group_id"].astype("Int32")
user_lessons_df["users_course_id"] = user_lessons_df["users_course_id"].astype("Int32")
user_lessons_df["solved_tasks_count"] = user_lessons_df["solved_tasks_count"].astype("Int16")
user_lessons_df["wk_points"] = user_lessons_df["wk_points"].astype("Float32")
user_lessons_df["wk_solved_task_count"] = user_lessons_df["wk_solved_task_count"].astype("Float32")
user_lessons_df[["video_visited", "translation_visited", "solved", "video_viewed"]] = user_lessons_df[["video_visited", "translation_visited", "solved", "video_viewed"]].astype("boolean")

user_activity_histories_df = pd.read_csv(
    SRC_DIR / "user_activity_histories.csv",
    usecols=["user_lesson_id", "action", "created_at"],
    parse_dates=["created_at"],
    thousands=",",
    low_memory=False,
)
user_activity_histories_df["user_lesson_id"] = user_activity_histories_df["user_lesson_id"].astype("Int32")
user_activity_histories_df["action"] = user_activity_histories_df["action"].astype("category")

wk_users_courses_actions_df = pd.read_csv(
    SRC_DIR / "wk_users_courses_actions.csv",
    usecols=["user_id", "users_course_id", "action", "created_at", "updated_at", "lesson_id"],
    parse_dates=["created_at", "updated_at"],
    thousands=",",
    low_memory=False,
)
wk_users_courses_actions_df["user_id"] = wk_users_courses_actions_df["user_id"].astype("Int32")
wk_users_courses_actions_df["users_course_id"] = wk_users_courses_actions_df["users_course_id"].astype("Int32")
wk_users_courses_actions_df["lesson_id"] = wk_users_courses_actions_df["lesson_id"].astype("Int32")
wk_users_courses_actions_df["action"] = wk_users_courses_actions_df["action"].astype("category")

In [ ]:
# Ответы, тренинги, бейджи и просмотр медиа.
user_answers_df = pd.read_csv(
    SRC_DIR / "user_answers.csv",
    usecols=[
        "user_id",
        "task_id",
        # "attempts", # константная колонка, не загружаем
        "solved",
        "points",
        "max_attempts",
        "skipped",
        "resource_type",
        "submitted_at",
        "wk_partial_answer",
        "async_check_status",
    ],
    parse_dates=["submitted_at"],
    thousands=",",
    low_memory=False,
)
user_answers_df["user_id"] = user_answers_df["user_id"].astype("Int32")
user_answers_df["task_id"] = user_answers_df["task_id"].astype("Int32")
user_answers_df["attempts"] = user_answers_df["attempts"].astype("Int8")
user_answers_df["points"] = user_answers_df["points"].astype("Float32")
user_answers_df["max_attempts"] = user_answers_df["max_attempts"].astype("Int8")
user_answers_df["async_check_status"] = user_answers_df["async_check_status"].astype("Int8")
user_answers_df["resource_type"] = user_answers_df["resource_type"].astype("category")
user_answers_df["solved"] = user_answers_df["solved"].replace({"True": True, "False": False}).astype("boolean")
user_answers_df["skipped"] = user_answers_df["skipped"].replace({"True": True, "False": False}).astype("boolean")
user_answers_df["wk_partial_answer"] = user_answers_df["wk_partial_answer"].replace({"True": True, "False": False}).astype("boolean")

user_trainings_df = pd.read_csv(
    SRC_DIR / "user_trainings.csv",
    usecols=[
        "user_id",
        "training_id",
        "solved_tasks_count",
        "earned_points",
        "type",
        "state",
        "submitted_answers_count",
        "started_at",
        "finished_at",
        "attempts",
        "mark",
        "mark_saved_at",
    ],
    thousands=",",
    low_memory=False,
)
user_trainings_df["started_at"] = pd.to_datetime(user_trainings_df["started_at"], format="%d %b, %Y, %H:%M", errors="coerce")
user_trainings_df["finished_at"] = pd.to_datetime(user_trainings_df["finished_at"], format="%d %b, %Y, %H:%M", errors="coerce")
user_trainings_df["mark_saved_at"] = pd.to_datetime(user_trainings_df["mark_saved_at"], format="%d %b, %Y, %H:%M", errors="coerce")
user_trainings_df["user_id"] = user_trainings_df["user_id"].astype("Int32")
user_trainings_df["training_id"] = user_trainings_df["training_id"].astype("Int32")
user_trainings_df["solved_tasks_count"] = user_trainings_df["solved_tasks_count"].astype("Int16")
user_trainings_df["earned_points"] = user_trainings_df["earned_points"].astype("Float32")
user_trainings_df["submitted_answers_count"] = user_trainings_df["submitted_answers_count"].astype("Int16")
user_trainings_df["attempts"] = user_trainings_df["attempts"].astype("Int8")
user_trainings_df["mark"] = user_trainings_df["mark"].astype("Float32")
user_trainings_df["type"] = user_trainings_df["type"].astype("category")
user_trainings_df["state"] = user_trainings_df["state"].astype("category")

user_award_badges_df = pd.read_csv(
    SRC_DIR / "user_award_badges.csv",
    usecols=["award_badge_id", "user_id", "created_at"],
    parse_dates=["created_at"],
    thousands=",",
    low_memory=False,
)
user_award_badges_df["award_badge_id"] = user_award_badges_df["award_badge_id"].astype("Int8")
user_award_badges_df["user_id"] = user_award_badges_df["user_id"].astype("Int32")

award_badges_df = pd.read_csv(
    SRC_DIR / "award_badges.csv",
    usecols=["title", "level", "quota", "special"],
    low_memory=False,
)
award_badges_df["title"] = award_badges_df["title"].astype("category")
award_badges_df["level"] = award_badges_df["level"].astype("Int8")
award_badges_df["quota"] = award_badges_df["quota"].astype("Int16")
award_badges_df["special"] = award_badges_df["special"].astype("boolean")

wk_media_view_sessions_df = pd.read_csv(
    SRC_DIR / "wk_media_view_sessions.csv",
    usecols=["resource_type", "viewer_id", "segments_total", "viewed_segments_count", "started_at", "kind"],
    thousands=",",
    low_memory=False,
)
wk_media_view_sessions_df["started_at"] = pd.to_datetime(wk_media_view_sessions_df["started_at"], format="%d %b, %Y, %H:%M", errors="coerce")
wk_media_view_sessions_df["resource_type"] = wk_media_view_sessions_df["resource_type"].astype("category")
wk_media_view_sessions_df["viewer_id"] = wk_media_view_sessions_df["viewer_id"].astype("Int32")
wk_media_view_sessions_df["segments_total"] = wk_media_view_sessions_df["segments_total"].astype("Int16")
wk_media_view_sessions_df["viewed_segments_count"] = wk_media_view_sessions_df["viewed_segments_count"].astype("Int16")
wk_media_view_sessions_df["kind"] = wk_media_view_sessions_df["kind"].astype("category")

In [10]:
dataframes = {
    "users_df": users_df,
    "users_courses_df": users_courses_df,
    "lessons_df": lessons_df,
    "user_access_histories_df": user_access_histories_df,
    "user_lessons_df": user_lessons_df,
    "user_activity_histories_df": user_activity_histories_df,
    "user_answers_df": user_answers_df,
    "user_trainings_df": user_trainings_df,
    "wk_users_courses_actions_df": wk_users_courses_actions_df,
    "wk_media_view_sessions_df": wk_media_view_sessions_df,
    "award_badges_df": award_badges_df,
    "user_award_badges_df": user_award_badges_df,
}

import_summary_df = pd.DataFrame(
    {
        "dataframe": list(dataframes.keys()),
        "rows": [df.shape[0] for df in dataframes.values()],
        "cols": [df.shape[1] for df in dataframes.values()],
        "memory_mb": [round(df.memory_usage(deep=True).sum() / 1024**2, 2) for df in dataframes.values()],
    }
).sort_values("memory_mb", ascending=False, ignore_index=True)

total_memory_mb = round(import_summary_df["memory_mb"].sum(), 2)

display(import_summary_df)
display(f"Суммарно в памяти: {total_memory_mb} MB")

                      dataframe      rows  cols  memory_mb
0               user_answers_df  15176182    11     521.03
1   wk_users_courses_actions_df  12909207     6     393.96
2               user_lessons_df   3070664    11     120.07
3    user_activity_histories_df   3031137     3      40.47
4             user_trainings_df    427628    12      22.02
5              users_courses_df    290835    12      19.69
6     wk_media_view_sessions_df    852358     6      17.07
7      user_access_histories_df    667124     4      14.00
8                      users_df     95395    15       5.75
9          user_award_badges_df    252843     3       3.62
10                   lessons_df      3369    11       0.12
11              award_badges_df         6     4       0.00

'Суммарно в памяти: 1157.8 MB'

## Аудит качества данных

Для первого прохода не усложняем и смотрим по каждой таблице:
- размер;
- `info()`;
- `describe()`.

После этого отдельно делаем несколько простых sanity checks по датам и ограничениям значений.

In [11]:
display(import_summary_df)

for name, df in dataframes.items():
    print(f"\n{name}: {df.shape[0]:,} rows x {df.shape[1]} cols")
    df.info(show_counts=True)
    display(df.describe(include="all").T)

                      dataframe      rows  cols  memory_mb
0               user_answers_df  15176182    11     521.03
1   wk_users_courses_actions_df  12909207     6     393.96
2               user_lessons_df   3070664    11     120.07
3    user_activity_histories_df   3031137     3      40.47
4             user_trainings_df    427628    12      22.02
5              users_courses_df    290835    12      19.69
6     wk_media_view_sessions_df    852358     6      17.07
7      user_access_histories_df    667124     4      14.00
8                      users_df     95395    15       5.75
9          user_award_badges_df    252843     3       3.62
10                   lessons_df      3369    11       0.12
11              award_badges_df         6     4       0.00

users_df: 95,395 rows x 15 cols
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95395 entries, 0 to 95394
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id                            95395 non-null  Int32
 1   last_explainer_seen_→_course  8217 non-null   Int8
 2   created_at                    95395 non-null  datetime64[ns]
 3   updated_at                    95395 non-null  datetime64[ns]
 4   type                          95395 non-null  category
 5   sign_in_count                 95395 non-null  Int32
 6   grade_id                      95395 non-null  Int16
 7   subscribed                    95395 non-null  boolean
 8   is_teacher                    95395 non-null  boolean
 9   timezone                      95217 non-null  category
 10  grade_changed_at              1804 non-null   datetime64[ns]
 11  d_wk_school_id                64093 non-null  Int32
 12  d_wk_municipal_id             64093 non-null  Int32
 13  d_wk_region_id                64093 non-null  Int32
 14  wk_gender                     15946 non-null  Int8
dtypes: Int16(1), Int32(5), Int8(2), boolean(2), category(2), datetime64[ns](3)
memory usage: 5.7 MB

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
id,95395.0,<NA>,<NA>,<NA>,713619.057257,665740.0,689652.5,713630.0,737571.5,761603.0,27654.314533
last_explainer_seen_→_course,8217.0,<NA>,<NA>,<NA>,6.382743,1.0,7.0,7.0,7.0,7.0,1.449124
created_at,95395,NaN,NaN,NaN,2025-09-02 10:04:45.591068928,2025-01-31 14:16:00,2025-06-05 19:58:30,2025-09-30 11:31:00,2025-11-12 08:38:00,2026-03-27 16:13:00,NaN
updated_at,95395,NaN,NaN,NaN,2025-11-25 07:39:32.594789888,2025-02-17 07:30:00,2025-11-18 20:30:30,2025-12-16 12:16:00,2025-12-25 01:55:00,2026-03-27 16:47:00,NaN
type,95395,2,User::Pupil,90647,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sign_in_count,95395.0,<NA>,<NA>,<NA>,18.956077,0.0,4.0,9.0,19.0,1390.0,37.564549
grade_id,95395.0,<NA>,<NA>,<NA>,3009.521076,3000.0,3010.0,3010.0,3010.0,3012.0,1.935844
subscribed,95395,2,True,94940,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_teacher,95395,1,False,95395,NaN,NaN,NaN,NaN,NaN,NaN,NaN
timezone,95217,141,Europe/Moscow,64085,NaN,NaN,NaN,NaN,NaN,NaN,NaN
grade_changed_at,1804,NaN,NaN,NaN,2025-08-30 03:11:38.148558848,2025-02-04 15:51:00,2025-06-11 10:44:45,2025-09-23 08:40:30,2025-10-28 10:24:15,2026-03-26 14:58:00,NaN
d_wk_school_id,64093.0,<NA>,<NA>,<NA>,170094.386407,93422.0,144581.0,144581.0,159759.0,331367.0,59300.616131
d_wk_municipal_id,64093.0,<NA>,<NA>,<NA>,157136.316478,93421.0,144580.0,144580.0,146830.0,331184.0,50642.44695
d_wk_region_id,64093.0,<NA>,<NA>,<NA>,156203.374097,93420.0,144579.0,144579.0,144671.0,286067.0,50634.957094
wk_gender,15946.0,<NA>,<NA>,<NA>,1.456854,1.0,1.0,1.0,2.0,2.0,0.498151

users_courses_df: 290,835 rows x 12 cols
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290835 entries, 0 to 290834
Data columns (total 12 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   user_id                   290835 non-null  Int32
 1   course_id                 290835 non-null  Int32
 2   state                     290835 non-null  category
 3   created_at                290835 non-null  datetime64[ns]
 4   updated_at                290835 non-null  datetime64[ns]
 5   access_finished_at        290741 non-null  datetime64[ns]
 6   wk_points                 205925 non-null  Float32
 7   wk_max_points             290710 non-null  Float32
 8   wk_max_viewable_lessons   290710 non-null  Float32
 9   wk_max_task_count         290710 non-null  Float32
 10  wk_officially_started_at  96865 non-null   datetime64[ns]
 11  wk_course_completed_at    354 non-null     datetime64[ns]
dtypes: Float32(4), Int32(2), category(1), datetime64[ns](5)
memory usage: 19.7 MB

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
user_id,290835.0,<NA>,<NA>,<NA>,715722.751409,665740.0,692031.0,716070.0,739958.0,761578.0,27293.035063
course_id,290835.0,<NA>,<NA>,<NA>,6916813.866577,754.0,770.0,771.0,836.0,170000688.0,29739455.750645
state,290835,2,active,287548,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_at,290835,NaN,NaN,NaN,2025-10-02 12:20:35.549848064,2025-02-07 11:33:00,2025-07-31 00:33:00,2025-11-05 12:25:00,2025-11-28 06:49:00,2026-03-26 20:23:00,NaN
updated_at,290835,NaN,NaN,NaN,2025-10-25 12:07:41.910774272,2025-02-19 07:00:00,2025-09-15 19:34:00,2025-11-19 13:03:00,2025-12-06 18:04:30,2026-03-27 01:49:00,NaN
access_finished_at,290741,NaN,NaN,NaN,2026-03-25 09:34:34.592850688,2025-02-16 00:00:00,2026-03-10 00:00:00,2026-05-06 00:00:00,2026-05-29 00:00:00,2026-09-26 00:00:00,NaN
wk_points,205925.0,<NA>,<NA>,<NA>,52.373169,0.0,28.0,52.299999,61.330002,492.079987,45.953308
wk_max_points,290710.0,<NA>,<NA>,<NA>,78.579185,0.0,4.0,63.0,79.0,1230.0,89.545662
wk_max_viewable_lessons,290710.0,<NA>,<NA>,<NA>,12.288298,0.0,5.0,14.0,14.0,80.0,7.222628
wk_max_task_count,290710.0,<NA>,<NA>,<NA>,82.034218,0.0,13.0,63.0,91.0,1230.0,91.185585
wk_officially_started_at,96865,NaN,NaN,NaN,2025-10-10 10:26:52.297527296,2023-06-21 00:00:00,2025-09-29 00:00:00,2025-11-07 00:00:00,2025-11-13 00:00:00,2026-02-23 00:00:00,NaN
wk_course_completed_at,354,NaN,NaN,NaN,2026-02-11 04:37:16.779661056,2026-01-12 14:35:00,2026-01-24 20:36:30,2026-02-08 00:31:00,2026-03-01 16:36:30,2026-03-26 17:26:00,NaN

lessons_df: 3,369 rows x 11 cols
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3369 entries, 0 to 3368
Data columns (total 11 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   course_id                           3369 non-null   Int32
 1   conspect_expected                   3369 non-null   bool
 2   task_expected                       3369 non-null   bool
 3   lesson_number                       845 non-null    Float32
 4   wk_max_points                       2759 non-null   Float32
 5   wk_task_count                       2759 non-null   Float32
 6   wk_survival_training_expected       3369 non-null   bool
 7   wk_scratch_playground_enabled       3369 non-null   bool
 8   wk_attendance_tracking_enabled      3369 non-null   bool
 9   wk_video_duration                   1646 non-null   Float32
 10  wk_attendance_tracking_disabled_at  2 non-null      datetime64[ns]
dtypes: Float32(4), Int32(1), bool(5), datetime64[ns](1)
memory usage: 125.1 KB

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
course_id,3369.0,<NA>,<NA>,<NA>,944834.568715,754.0,890.0,936.0,1032.0,170000688.0,10041430.120071
conspect_expected,3369,2,True,2204,NaN,NaN,NaN,NaN,NaN,NaN,NaN
task_expected,3369,2,True,2477,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lesson_number,845.0,<NA>,<NA>,<NA>,25.171598,1.0,7.0,15.0,36.0,115.0,25.896364
wk_max_points,2759.0,<NA>,<NA>,<NA>,8.767089,0.0,4.0,8.0,13.0,24.0,5.905985
wk_task_count,2759.0,<NA>,<NA>,<NA>,8.815875,0.0,4.0,7.0,13.0,23.0,5.807663
wk_survival_training_expected,3369,2,False,3367,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wk_scratch_playground_enabled,3369,2,False,3351,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wk_attendance_tracking_enabled,3369,2,False,2771,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wk_video_duration,1646.0,<NA>,<NA>,<NA>,4.744228,1.0,1.0,1.0,8.0,31.0,6.81456
wk_attendance_tracking_disabled_at,2,NaN,NaN,NaN,2026-01-06 04:45:00,2025-12-23 22:25:00,2025-12-30 13:35:00,2026-01-06 04:45:00,2026-01-12 19:55:00,2026-01-19 11:05:00,NaN

user_access_histories_df: 667,124 rows x 4 cols
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667124 entries, 0 to 667123
Data columns (total 4 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   users_course_id    667124 non-null  Int32
 1   access_started_at  667124 non-null  datetime64[ns]
 2   access_expired_at  667124 non-null  datetime64[ns]
 3   activator_class    667124 non-null  category
dtypes: Int32(1), category(1), datetime64[ns](2)
memory usage: 14.0 MB

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
users_course_id,667124.0,<NA>,<NA>,<NA>,625565.198728,449032.0,595276.75,648983.0,668843.0,746426.0,68844.332772
access_started_at,667124,NaN,NaN,NaN,2025-10-29 08:07:00.047847168,2025-02-07 00:00:00,2025-11-03 00:00:00,2025-11-21 00:00:00,2025-11-27 00:00:00,2026-03-27 00:00:00,NaN
access_expired_at,667124,NaN,NaN,NaN,2026-04-22 21:30:17.753821184,2025-02-16 00:00:00,2026-05-05 00:00:00,2026-05-21 00:00:00,2026-05-27 00:00:00,2026-09-27 00:00:00,NaN
activator_class,667124,5,Courses::AccessActivators::PremiumAccessActivator,665443,NaN,NaN,NaN,NaN,NaN,NaN,NaN

user_lessons_df: 3,070,664 rows x 11 cols
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3070664 entries, 0 to 3070663
Data columns (total 11 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   user_id               3070664 non-null  Int32
 1   lesson_id             3070664 non-null  Int32
 2   group_id              3070664 non-null  Int32
 3   video_visited         3070664 non-null  boolean
 4   translation_visited   3070664 non-null  boolean
 5   users_course_id       3070664 non-null  Int32
 6   solved                3070664 non-null  boolean
 7   solved_tasks_count    3070664 non-null  Int16
 8   wk_points             2885646 non-null  Float32
 9   video_viewed          3070664 non-null  boolean
 10  wk_solved_task_count  2885646 non-null  Float32
dtypes: Float32(2), Int16(1), Int32(4), boolean(4)
memory usage: 120.1 MB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
user_id,3070664.0,<NA>,<NA>,<NA>,720944.918086,23866.028589,665743.0,703841.75,722480.0,741221.0,761712.0
lesson_id,3070664.0,<NA>,<NA>,<NA>,2596776.774844,17888320.058307,5628.0,5954.0,6063.0,6145.0,170005400.0
group_id,3070664.0,<NA>,<NA>,<NA>,2597246.344213,17888270.005791,5751.0,6077.0,6186.0,6268.0,170005523.0
video_visited,3070664,2,True,2471536,NaN,NaN,NaN,NaN,NaN,NaN,NaN
translation_visited,3070664,2,False,3008441,NaN,NaN,NaN,NaN,NaN,NaN,NaN
users_course_id,3070664.0,<NA>,<NA>,<NA>,623851.261493,79580.226281,449037.0,554085.75,635092.0,695167.0,746583.0
solved,3070664,2,True,2742883,NaN,NaN,NaN,NaN,NaN,NaN,NaN
solved_tasks_count,3070664.0,<NA>,<NA>,<NA>,4.723881,4.078911,0.0,3.0,3.0,5.0,24.0
wk_points,2885646.0,<NA>,<NA>,<NA>,3.820454,3.443585,0.0,2.0,3.0,3.5,24.0
video_viewed,3070664,2,False,2971014,NaN,NaN,NaN,NaN,NaN,NaN,NaN
wk_solved_task_count,2885646.0,<NA>,<NA>,<NA>,5.026797,4.022327,0.0,3.0,3.0,5.0,23.0

user_activity_histories_df: 3,031,137 rows x 3 cols
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3031137 entries, 0 to 3031136
Data columns (total 3 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   user_lesson_id  3031137 non-null  Int32
 1   action          3031137 non-null  category
 2   created_at      3031137 non-null  datetime64[ns]
dtypes: Int32(1), category(1), datetime64[ns](1)
memory usage: 40.5 MB

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
user_lesson_id,3031137.0,<NA>,<NA>,<NA>,1688386.591862,1.0,933488.0,1628707.0,2460716.0,3314363.0,895284.993872
action,3031137,3,visit_video,2642950,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_at,3031137,NaN,NaN,NaN,2025-11-05 09:42:31.950545920,2020-11-25 13:36:00,2025-10-22 04:04:00,2025-11-25 13:27:00,2025-12-08 18:53:00,2026-03-31 15:20:00,NaN

user_answers_df: 15,176,182 rows x 11 cols
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15176182 entries, 0 to 15176181
Data columns (total 11 columns):
 #   Column              Non-Null Count     Dtype
---  ------              --------------     -----
 0   user_id             15176182 non-null  Int32
 1   task_id             15176182 non-null  Int32
 2   attempts            15176182 non-null  Int8
 3   solved              15049902 non-null  boolean
 4   points              15176182 non-null  Float32
 5   max_attempts        15176182 non-null  Int8
 6   skipped             4918162 non-null   boolean
 7   resource_type       15176182 non-null  category
 8   submitted_at        15040666 non-null  datetime64[ns]
 9   wk_partial_answer   4918162 non-null   boolean
 10  async_check_status  15176182 non-null  Int8
dtypes: Float32(1), Int32(2), Int8(3), boolean(3), category(1), datetime64[ns](1)
memory usage: 521.0 MB

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
user_id,15176182.0,<NA>,<NA>,<NA>,722187.305532,665745.0,706326.0,724550.0,740836.0,761666.0,22761.669105
task_id,15176182.0,<NA>,<NA>,<NA>,2635092.317635,1000213.0,1167821.0,1170095.0,1173440.0,200000282.0,17005143.555435
attempts,15176182.0,<NA>,<NA>,<NA>,0.991692,0.0,1.0,1.0,1.0,2.0,0.090905
solved,15049902,2,True,11860153,NaN,NaN,NaN,NaN,NaN,NaN,NaN
points,15176182.0,<NA>,<NA>,<NA>,0.767647,0.0,0.7,1.0,1.0,42.0,0.55541
max_attempts,15176182.0,<NA>,<NA>,<NA>,1.00002,1.0,1.0,1.0,1.0,2.0,0.004424
skipped,4918162,2,False,4908190,NaN,NaN,NaN,NaN,NaN,NaN,NaN
resource_type,15176182,3,Lesson,9848739,NaN,NaN,NaN,NaN,NaN,NaN,NaN
submitted_at,15040666,NaN,NaN,NaN,2025-11-19 03:30:34.308410368,2025-02-17 16:43:00,2025-11-14 16:43:00,2025-11-28 05:04:00,2025-12-09 04:17:00,2026-03-31 16:04:00,NaN
wk_partial_answer,4918162,2,False,4907978,NaN,NaN,NaN,NaN,NaN,NaN,NaN
async_check_status,15176182.0,<NA>,<NA>,<NA>,0.122708,0.0,0.0,0.0,0.0,2.0,0.479956

user_trainings_df: 427,628 rows x 12 cols
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 427628 entries, 0 to 427627
Data columns (total 12 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   user_id                  427628 non-null  Int32
 1   training_id              427628 non-null  Int32
 2   solved_tasks_count       427628 non-null  Int16
 3   earned_points            424311 non-null  Float32
 4   type                     427628 non-null  category
 5   state                    427628 non-null  category
 6   submitted_answers_count  427628 non-null  Int16
 7   started_at               427628 non-null  datetime64[ns]
 8   finished_at              424311 non-null  datetime64[ns]
 9   attempts                 427628 non-null  Int8
 10  mark                     424311 non-null  Float32
 11  mark_saved_at            424311 non-null  datetime64[ns]
dtypes: Float32(2), Int16(2), Int32(2), Int8(1), category(2), datetime64[ns](3)
memory usage: 22.0 MB

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
user_id,427628.0,<NA>,<NA>,<NA>,721932.084721,665745.0,704900.75,723800.0,741783.0,761508.0,23314.405762
training_id,427628.0,<NA>,<NA>,<NA>,740554.879552,2353.0,2383.0,2419.0,2452.0,170002293.0,8019585.521813
solved_tasks_count,427628.0,<NA>,<NA>,<NA>,11.274264,0.0,7.0,15.0,15.0,20.0,4.516531
earned_points,424311.0,<NA>,<NA>,<NA>,8.120891,0.0,4.25,8.4,13.0,100.0,5.80133
type,427628,3,UserTrainings::LessonTraining,416960,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state,427628,2,checked,424311,NaN,NaN,NaN,NaN,NaN,NaN,NaN
submitted_answers_count,427628.0,<NA>,<NA>,<NA>,11.266505,0.0,7.0,13.0,15.0,20.0,4.497667
started_at,427628,NaN,NaN,NaN,2025-11-17 07:20:46.718361856,2025-02-17 08:47:00,2025-11-06 07:38:45,2025-11-28 14:26:00,2025-12-09 14:45:00,2026-03-27 17:07:00,NaN
finished_at,424311,NaN,NaN,NaN,2025-11-18 00:48:35.111037952,2025-02-17 16:44:00,2025-11-06 21:06:30,2025-11-28 18:54:00,2025-12-09 15:59:00,2026-03-27 17:06:00,NaN
attempts,427628.0,<NA>,<NA>,<NA>,1.0,1.0,1.0,1.0,1.0,1.0,0.0
mark,424311.0,<NA>,<NA>,<NA>,4.069656,2.0,4.0,4.0,5.0,5.0,1.104904
mark_saved_at,424311,NaN,NaN,NaN,2025-11-18 02:51:09.445901568,2025-02-17 16:44:00,2025-11-06 21:06:30,2025-11-28 18:54:00,2025-12-09 15:59:00,2026-03-27 17:06:00,NaN

wk_users_courses_actions_df: 12,909,207 rows x 6 cols
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12909207 entries, 0 to 12909206
Data columns (total 6 columns):
 #   Column           Non-Null Count     Dtype
---  ------           --------------     -----
 0   user_id          12909207 non-null  Int32
 1   users_course_id  12909207 non-null  Int32
 2   action           12909207 non-null  category
 3   created_at       12909207 non-null  datetime64[ns]
 4   updated_at       12909207 non-null  datetime64[ns]
 5   lesson_id        15071 non-null     Int32
dtypes: Int32(3), category(1), datetime64[ns](2)
memory usage: 394.0 MB

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
user_id,12909207.0,<NA>,<NA>,<NA>,719250.037085,665743.0,704151.0,719680.0,737862.0,761721.0,23184.143099
users_course_id,12909207.0,<NA>,<NA>,<NA>,624925.473316,449037.0,557264.0,633913.0,698541.0,746596.0,81299.399122
action,12909207,6,user_answer,9698443,NaN,NaN,NaN,NaN,NaN,NaN,NaN
created_at,12909207,NaN,NaN,NaN,2025-11-17 16:25:12.832713728,2025-02-17 11:35:00,2025-10-31 08:52:00,2025-11-27 12:40:00,2025-12-11 09:55:00,2026-03-31 14:12:00,NaN
updated_at,12909207,NaN,NaN,NaN,2025-11-17 16:25:17.221354240,2025-02-17 11:35:00,2025-10-31 08:52:00,2025-11-27 12:40:00,2025-12-11 09:55:00,2026-03-31 14:12:00,NaN
lesson_id,15071.0,<NA>,<NA>,<NA>,36804116.448345,5659.0,5934.0,50004609.0,50004618.0,50004637.0,22040565.618887

wk_media_view_sessions_df: 852,358 rows x 6 cols
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 852358 entries, 0 to 852357
Data columns (total 6 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   resource_type          852358 non-null  category
 1   viewer_id              852358 non-null  Int32
 2   segments_total         852358 non-null  Int16
 3   viewed_segments_count  852358 non-null  Int16
 4   started_at             852358 non-null  datetime64[ns]
 5   kind                   852358 non-null  category
dtypes: Int16(2), Int32(1), category(2), datetime64[ns](1)
memory usage: 17.1 MB

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
resource_type,852358,2,Lesson,619576,NaN,NaN,NaN,NaN,NaN,NaN,NaN
viewer_id,852358.0,<NA>,<NA>,<NA>,722081.52668,665744.0,704571.0,720112.0,741622.0,761599.0,22483.214357
segments_total,852358.0,<NA>,<NA>,<NA>,18.296854,1.0,8.0,10.0,37.0,190.0,17.155832
viewed_segments_count,852358.0,<NA>,<NA>,<NA>,11.93938,1.0,2.0,8.0,11.0,186.0,13.878893
started_at,852358,NaN,NaN,NaN,2025-11-24 09:50:05.723439872,2025-03-28 05:58:00,2025-11-01 12:35:00,2025-11-30 17:59:00,2025-12-12 05:27:00,2026-03-27 14:08:00,NaN
kind,852358,3,kinescope,619576,NaN,NaN,NaN,NaN,NaN,NaN,NaN

award_badges_df: 6 rows x 4 cols
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    6 non-null      category
 1   level    6 non-null      Int8
 2   quota    6 non-null      Int16
 3   special  6 non-null      boolean
dtypes: Int16(1), Int8(1), boolean(1), category(1)
memory usage: 300.0 bytes

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
title,6,2,Я решаю,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
level,6.0,<NA>,<NA>,<NA>,2.666667,1.632993,1.0,1.25,2.5,3.75,5.0
quota,6.0,<NA>,<NA>,<NA>,113.5,192.799118,1.0,10.0,37.5,87.5,500.0
special,6,2,False,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN

user_award_badges_df: 252,843 rows x 3 cols
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252843 entries, 0 to 252842
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   award_badge_id  252843 non-null  Int8
 1   user_id         252843 non-null  Int32
 2   created_at      252843 non-null  datetime64[ns]
dtypes: Int32(1), Int8(1), datetime64[ns](1)
memory usage: 3.6 MB

,count,mean,min,25%,50%,75%,max,std
award_badge_id,252843.0,3.406205,1.0,2.0,3.0,4.0,6.0,1.186196
user_id,252843.0,719383.88025,663004.0,701568.0,721099.0,741223.0,761575.0,25648.447885
created_at,252843,2025-10-16 12:11:16.355762432,2023-10-03 12:53:00,2025-10-11 20:16:30,2025-11-17 07:44:00,2025-11-30 21:33:30,2026-03-27 17:18:00,NaN

По min/max значениям не нашла странных числел - напаример, отрицательных. 

user_trainings_df["attempts"]: min=max=1 -- колонка константная, бесполезна как фича.

## Проверка на дубли

In [22]:
# Полные дубли строк по всем импортированным таблицам.
duplicates_df = pd.DataFrame(
    {
        "dataframe": list(dataframes.keys()),
        "duplicate_rows": [int(df.duplicated().sum()) for df in dataframes.values()],
        "share_pct": [round(df.duplicated().mean() * 100, 4) for df in dataframes.values()],
    }
).sort_values(["duplicate_rows", "dataframe"], ascending=[False, True], ignore_index=True)

display(duplicates_df)

                      dataframe  duplicate_rows  share_pct
0   wk_users_courses_actions_df         5491157    42.5367
1               user_answers_df         4951291    32.6254
2      user_access_histories_df          355372    53.2693
3    user_activity_histories_df           33312     1.0990
4     wk_media_view_sessions_df           22183     2.6025
5                    lessons_df            1813    53.8142
6               award_badges_df               0     0.0000
7          user_award_badges_df               0     0.0000
8               user_lessons_df               0     0.0000
9             user_trainings_df               0     0.0000
10             users_courses_df               0     0.0000
11                     users_df               0     0.0000

### Sanity Checks

Следующая ячейка проверяет только базовые ограничения в основных таблицах: порядок дат, факт не превышает максимум и явные дубли в естественных ключах.

In [21]:
sanity_checks_df = pd.DataFrame(
    {
        "table": [
            "users_df",
            "users_df",
            "lessons_df",
            "user_access_histories_df",
            "user_lessons_df",
            "user_lessons_df",
            "user_answers_df",
            "user_trainings_df",
            "user_trainings_df",
            "users_courses_df",
            "users_courses_df",
            "users_courses_df",
            "users_courses_df",
            "users_courses_df",
            "wk_users_courses_actions_df",
            "wk_media_view_sessions_df",
        ],
        "check": [
            "updated_at < created_at",
            "grade_changed_at < created_at",
            "lesson_number <= 0",
            "access_expired_at < access_started_at",
            "solved_tasks_count > wk_solved_task_count",
            "duplicate (user_id, users_course_id, lesson_id)",
            "attempts > max_attempts",
            "finished_at < started_at",
            "mark_saved_at < finished_at",
            "wk_points > wk_max_points",
            "wk_officially_started_at > access_finished_at",
            "wk_course_completed_at < created_at",
            "wk_course_completed_at < wk_officially_started_at",
            "duplicate (user_id, course_id)",
            "updated_at < created_at",
            "viewed_segments_count > segments_total",
        ],
        "bad_rows": [
            int((users_df["updated_at"] < users_df["created_at"]).sum()),
            int((users_df["grade_changed_at"] < users_df["created_at"]).sum()),
            int((lessons_df["lesson_number"] <= 0).sum()),
            int((user_access_histories_df["access_expired_at"] < user_access_histories_df["access_started_at"]).sum()),
            int((user_lessons_df["solved_tasks_count"] > user_lessons_df["wk_solved_task_count"]).sum()),
            int(user_lessons_df.duplicated(["user_id", "users_course_id", "lesson_id"]).sum()),
            int((user_answers_df["attempts"] > user_answers_df["max_attempts"]).sum()),
            int((user_trainings_df["finished_at"] < user_trainings_df["started_at"]).sum()),
            int((user_trainings_df["mark_saved_at"] < user_trainings_df["finished_at"]).sum()),
            int((users_courses_df["wk_points"] > users_courses_df["wk_max_points"]).sum()),
            int((users_courses_df["wk_officially_started_at"] > users_courses_df["access_finished_at"]).sum()),
            int((users_courses_df["wk_course_completed_at"] < users_courses_df["created_at"]).sum()),
            int((users_courses_df["wk_course_completed_at"] < users_courses_df["wk_officially_started_at"]).sum()),
            int(users_courses_df.duplicated(["user_id", "course_id"]).sum()),
            int((wk_users_courses_actions_df["updated_at"] < wk_users_courses_actions_df["created_at"]).sum()),
            int((wk_media_view_sessions_df["viewed_segments_count"] > wk_media_view_sessions_df["segments_total"]).sum()),
        ],
    }
)

table_rows = {name: df.shape[0] for name, df in dataframes.items()}
sanity_checks_df["share_pct"] = (sanity_checks_df["bad_rows"] / sanity_checks_df["table"].map(table_rows) * 100).round(4)

display(sanity_checks_df.sort_values(["bad_rows", "table"], ascending=[False, True], ignore_index=True))

,table,check,bad_rows,share_pct
0,user_access_histories_df,access_expired_at < access_started_at,2757,0.4133
1,user_answers_df,attempts > max_attempts,190,0.0013
2,users_courses_df,wk_points > wk_max_points,179,0.0615
3,user_lessons_df,solved_tasks_count > wk_solved_task_count,151,0.0049
4,user_trainings_df,mark_saved_at < finished_at,59,0.0138
5,users_courses_df,wk_officially_started_at > access_finished_at,2,0.0007
6,wk_users_courses_actions_df,updated_at < created_at,1,0.0000
7,lessons_df,lesson_number <= 0,0,0.0000
8,user_lessons_df,"duplicate (user_id, users_course_id, lesson_id)",0,0.0000
9,user_trainings_df,finished_at < started_at,0,0.0000
10,users_courses_df,wk_course_completed_at < created_at,0,0.0000
11,users_courses_df,wk_course_completed_at < wk_officially_started_at,0,0.0000
12,users_courses_df,"duplicate (user_id, course_id)",0,0.0000
13,users_df,updated_at < created_at,0,0.0000
14,users_df,grade_changed_at < created_at,0,0.0000
15,wk_media_view_sessions_df,viewed_segments_count > segments_total,0,0.0000

## Найденные проблемы со связностью

В users_courses.csv отсутствует users_course_id, поэтому эту таблицу нельзя напрямую связать с user_lessons.csv, wk_users_courses_actions.csv и user_access_histories.csv, где users_course_id есть.

В user_activity_histories.csv есть user_lesson_id, но в user_lessons.csv отсутствует user_lesson_id, поэтому user_activity_histories.csv нельзя напрямую связать ни с одной другой таблицей.

В lessons.csv отсутствует lesson_id, поэтому эту таблицу нельзя напрямую связать с user_lessons.csv и wk_users_courses_actions.csv, где lesson_id есть и по документации ссылается на урок из lessons.

В user_answers.csv отсутствует resource_id из документации, а также нет lesson_id, course_id и users_course_id, поэтому эту таблицу нельзя напрямую связать с lessons.csv, user_lessons.csv, users_courses.csv и wk_users_courses_actions.csv на уровне конкретного урока или курса.

В award_badges.csv отсутствует award_badge_id, поэтому эту таблицу нельзя напрямую связать с user_award_badges.csv, где award_badge_id есть.

В wk_media_view_sessions.csv отсутствуют lesson_id, course_id и users_course_id, поэтому эту таблицу нельзя напрямую связать с course-level блоком: users_courses.csv, user_lessons.csv, lessons.csv, wk_users_courses_actions.csv. Она связана только с пользователем через viewer_id.